spring:
  application:
    name: clientes-soap
  config:
    import: optional:configserver:http://config-server
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
