spring.application.name=citas-soap-service
# Configuración de la base de datos H2 (en memoria)
# jdbc:h2:mem:citasdb - Define una base de datos en memoria llamada 'citasdb'
spring.datasource.url=jdbc:h2:mem:medicals
spring.datasource.driverClassName=org.h2.Driver # Driver para H2
spring.datasource.username=sa # Usuario por defecto para H2
spring.datasource.password= # Contraseña vacía por defecto
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect # Dialecto de Hibernate para H2
# 'update' - Hibernate intentará actualizar el esquema de la base de datos para que coincida con las entidades JPA
spring.jpa.hibernate.ddl-auto=update 
spring.h2.console.enabled=true 
spring.h2.console.path=/h2-console # Ruta para acceder a la consola H2 (ej. http://localhost:8080/h2-console)

# Configuración del servidor web integrado (Tomcat por defecto)
server.port=8080
